"""empty message

Revision ID: e70c432e21b1
Revises: e1b0a35c67ad
Create Date: 2019-04-25 23:31:45.768405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70c432e21b1'
down_revision = 'e1b0a35c67ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.String(length=10), nullable=True),
    sa.Column('descricao', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=150), nullable=True),
    sa.Column('campanha', sa.String(length=200), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('quantidade_recebida', sa.String(length=200), nullable=True),
    sa.Column('unidade', sa.String(length=200), nullable=True),
    sa.Column('nome_doador', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juridico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
    sa.Column('CNPJ', sa.String(length=20), nullable=True),
    sa.Column('end_comercial', sa.String(length=200), nullable=True),
    sa.Column('complemento_comercial', sa.String(length=200), nullable=True),
    sa.Column('bairro_comercial', sa.String(length=50), nullable=True),
    sa.Column('cep_comercial', sa.String(length=10), nullable=True),
    sa.Column('fone1', sa.String(length=30), nullable=True),
    sa.Column('fone2', sa.String(length=30), nullable=True),
    sa.Column('fone3', sa.String(length=30), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('como_soube_rssa', sa.String(length=30), nullable=True),
    sa.Column('motivacao', sa.String(length=30), nullable=True),
    sa.Column('expectativa', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_fantasia')
    )
    op.create_table('parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_oferta', sa.String(length=20), nullable=False),
    sa.Column('descricao_oferta', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsavel_legal', sa.String(length=200), nullable=False),
    sa.Column('cpf_responsavel_legal', sa.String(length=14), nullable=True),
    sa.Column('email_responsavel_legal', sa.String(length=30), nullable=True),
    sa.Column('grau_parentesco_id', sa.Integer(), nullable=True),
    sa.Column('endereco_residencial', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('fone_representante_legal', sa.String(length=30), nullable=True),
    sa.Column('celular_representante_legal', sa.String(length=30), nullable=True),
    sa.Column('email_representante_legal', sa.String(length=30), nullable=True),
    sa.Column('ind_contexto_familiar', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responsavel_legal')
    )
    op.create_table('unidade_solicitante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('data_nasc', sa.String(length=10), nullable=True),
    sa.Column('RG', sa.String(length=20), nullable=True),
    sa.Column('orgao_exp', sa.String(length=30), nullable=True),
    sa.Column('CPF', sa.String(length=14), nullable=True),
    sa.Column('end_residencial', sa.String(length=200), nullable=True),
    sa.Column('complemento_residencial', sa.String(length=200), nullable=True),
    sa.Column('bairro_residencial', sa.String(length=50), nullable=True),
    sa.Column('cep_residencial', sa.String(length=10), nullable=True),
    sa.Column('fone', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('como_soube_rssa', sa.String(length=30), nullable=True),
    sa.Column('motivacao', sa.String(length=30), nullable=True),
    sa.Column('expectativa', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('atuacaopf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acoes_id', sa.Integer(), nullable=True),
    sa.Column('data_inscricao', sa.String(length=20), nullable=True),
    sa.Column('data_entrevista', sa.String(length=20), nullable=True),
    sa.Column('tratativas', sa.String(length=400), nullable=True),
    sa.Column('data_adesao', sa.String(length=20), nullable=True),
    sa.Column('atividade', sa.String(length=30), nullable=True),
    sa.Column('especialidade', sa.String(length=30), nullable=True),
    sa.Column('experiencia_anterior', sa.String(length=10), nullable=True),
    sa.Column('quais_experiencias', sa.String(length=200), nullable=True),
    sa.Column('disponibilidade', sa.String(length=30), nullable=True),
    sa.Column('deslocamentos_possiveis', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['acoes_id'], ['voluntario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atuacaopj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acoes_id', sa.Integer(), nullable=True),
    sa.Column('data_inscricao', sa.String(length=20), nullable=True),
    sa.Column('data_entrevista', sa.String(length=20), nullable=True),
    sa.Column('tratativas', sa.String(length=400), nullable=True),
    sa.Column('data_adesao', sa.String(length=20), nullable=True),
    sa.Column('atividade', sa.String(length=30), nullable=True),
    sa.Column('especialidade', sa.String(length=30), nullable=True),
    sa.Column('experiencia_anterior', sa.String(length=10), nullable=True),
    sa.Column('quais_experiencias', sa.String(length=200), nullable=True),
    sa.Column('disponibilidade', sa.String(length=30), nullable=True),
    sa.Column('deslocamentos_possiveis', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['acoes_id'], ['juridico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dado_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dado_id', sa.Integer(), nullable=True),
    sa.Column('formacao', sa.String(length=150), nullable=True),
    sa.Column('escolaridade', sa.String(length=50), nullable=True),
    sa.Column('atuacao_em_anos', sa.Integer(), nullable=True),
    sa.Column('outros_cursos', sa.String(length=200), nullable=True),
    sa.Column('registro_profissional', sa.String(length=50), nullable=True),
    sa.Column('cargo_servidor', sa.String(length=50), nullable=True),
    sa.Column('ocupacao_atual', sa.String(length=50), nullable=True),
    sa.Column('end_comercial', sa.String(length=200), nullable=True),
    sa.Column('complemento_comercial', sa.String(length=200), nullable=True),
    sa.Column('bairro_comercial', sa.String(length=50), nullable=True),
    sa.Column('cep_comercial', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dado_id'], ['voluntario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jurisdicionado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('data_nasc', sa.String(length=10), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('RG', sa.String(length=20), nullable=True),
    sa.Column('orgao_exp', sa.String(length=30), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('genitor', sa.String(length=200), nullable=True),
    sa.Column('cpf_genitor', sa.String(length=14), nullable=True),
    sa.Column('genitora', sa.String(length=200), nullable=True),
    sa.Column('cpf_genitora', sa.String(length=14), nullable=True),
    sa.Column('fone_jurisdicionado', sa.String(length=30), nullable=True),
    sa.Column('email_jurisdicionado', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=30), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('escolaridade', sa.String(length=10), nullable=True),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.Column('instituicao_educacional', sa.String(length=200), nullable=True),
    sa.Column('fone_instituicao', sa.String(length=30), nullable=True),
    sa.Column('desempenho_escolar', sa.String(length=10), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('representante_legal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=60), nullable=True),
    sa.Column('RG', sa.String(length=20), nullable=True),
    sa.Column('orgao_exp', sa.String(length=30), nullable=True),
    sa.Column('CPF', sa.String(length=14), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['juridico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_saida', sa.String(length=20), nullable=True),
    sa.Column('entrega_id', sa.Integer(), nullable=True),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('beneficiario', sa.String(length=60), nullable=True),
    sa.Column('processo_nr', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('quantidade_doada', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrada.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destino')
    )
    op.create_table('vinculapf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=True),
    sa.Column('beneficiario', sa.String(length=200), nullable=True),
    sa.Column('detalhamento', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['voluntario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculapj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=True),
    sa.Column('beneficiario', sa.String(length=200), nullable=True),
    sa.Column('detalhamento', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['juridico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vinculo_id', sa.Integer(), nullable=True),
    sa.Column('nr_processo', sa.String(length=50), nullable=True),
    sa.Column('origem', sa.String(length=10), nullable=True),
    sa.Column('unid_solicitante_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_resp', sa.String(length=100), nullable=True),
    sa.Column('data_solicitacao', sa.String(length=20), nullable=True),
    sa.Column('descricao_solicitacao', sa.String(length=300), nullable=True),
    sa.Column('prazo_cumprimento_meses', sa.Integer(), nullable=True),
    sa.Column('data_cumprimento', sa.String(length=20), nullable=True),
    sa.Column('status_cumprimento', sa.String(length=10), nullable=True),
    sa.Column('pasta', sa.String(length=10), nullable=True),
    sa.Column('subpasta', sa.String(length=10), nullable=True),
    sa.Column('qual_curso', sa.String(length=100), nullable=True),
    sa.Column('sugestao_da_instituicao', sa.String(length=200), nullable=True),
    sa.Column('servidor_resp', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['unid_solicitante_id'], ['unidade_solicitante.id'], ),
    sa.ForeignKeyConstraint(['vinculo_id'], ['jurisdicionado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demanda_id', sa.Integer(), nullable=True),
    sa.Column('parceiro_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_ini', sa.String(length=20), nullable=True),
    sa.Column('data_fim', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['demanda_id'], ['demanda.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vinculacao')
    op.drop_table('demanda')
    op.drop_table('vinculapj')
    op.drop_table('vinculapf')
    op.drop_table('saida')
    op.drop_table('representante_legal')
    op.drop_table('jurisdicionado')
    op.drop_table('dado_profissional')
    op.drop_table('atuacaopj')
    op.drop_table('atuacaopf')
    op.drop_table('voluntario')
    op.drop_table('unidade_solicitante')
    op.drop_table('responsavel')
    op.drop_table('parceiro')
    op.drop_table('juridico')
    op.drop_table('entrada')
    # ### end Alembic commands ###
