version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
    - ./postgres-data/postgres:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/code # for development only
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    entrypoint: ["python3", "app.py"]


      